import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';

import type { CaptionPlacement } from './caption.js';

/**
 * A take: everything one capture run produced.
 *
 * Capture drives the application once and writes a take. Composition reads it
 * and cuts a video. Keeping them apart is the whole point of this design: a
 * take costs minutes and a cut costs seconds, so timing stops being something
 * you have to re-record and becomes something you edit.
 *
 * A take is scratch. It is large, it is regenerated by `npm run record`, and
 * `demo/takes/` is not tracked. The mp4 files it produces are the deliverable.
 */

const ROOT = path.resolve(__dirname, '../..');

/** Where every take lives. One directory per timeline name. */
export const TAKES_DIR = path.join(ROOT, 'demo', 'takes');

/** One captured still. `file` is relative to the take directory. */
export interface Frame {
  at: number;
  file: string;
}

/**
 * A named instant a sequence chose to remember.
 *
 * Marks are how an edit refers to a moment without guessing at a second. A
 * timeline that waits for an approval prompt can mark that instant, and the
 * edit can then freeze on `approval-shown` and stay correct even when the next
 * capture takes two seconds longer to get there.
 */
export interface Mark {
  label: string;
  at: number;
}

/**
 * A card, rendered to a transparent image beside the frames.
 *
 * Sizes are in output pixels with the transparent margin included. The margin
 * exists because the card carries a drop shadow that would otherwise be cut
 * off at the edge of the clip.
 */
export interface CardRef {
  file: string;
  placement: CaptionPlacement;
  width: number;
  height: number;
  margin: number;
  /** Device pixels per output pixel the image was rendered at. */
  scale: number;
}

export interface Sequence {
  /** Stable name an edit refers to. Unique within a take. */
  id: string;
  /** Heading shown on the card. */
  name: string;
  note?: string;
  card?: CardRef;
  /** Wall clock milliseconds when `drive` started and when it settled. */
  startedAt: number;
  endedAt: number;
  marks: Mark[];
  /**
   * Frames for this sequence, in arrival order.
   *
   * The first entry is the last frame captured at or before `startedAt`, so a
   * sequence always opens on a real picture. A screencast only emits when
   * something changes, and a sequence that begins on a still screen would
   * otherwise have nothing to show until the first change.
   */
  frames: Frame[];
}

export interface Take {
  name: string;
  width: number;
  height: number;
  fps: number;
  sequences: Sequence[];
}

export function takeDir(name: string): string {
  return path.join(TAKES_DIR, name);
}

/** Resolve a path recorded inside a take. */
export function inTake(name: string, relative: string): string {
  return path.join(takeDir(name), relative);
}

/** Empty a take directory and lay out the folders a capture writes into. */
export async function resetTake(name: string): Promise<string> {
  const dir = takeDir(name);
  await rm(dir, { recursive: true, force: true });
  await mkdir(path.join(dir, 'frames'), { recursive: true });
  await mkdir(path.join(dir, 'cards'), { recursive: true });
  return dir;
}

export async function writeTake(take: Take): Promise<void> {
  await writeFile(
    path.join(takeDir(take.name), 'take.json'),
    `${JSON.stringify(take, null, 2)}\n`,
  );
}

/**
 * Read a take, and say what to run when it is not there.
 *
 * A missing take is the ordinary case on a fresh checkout, because takes are
 * not tracked. The message has to name the command that produces one.
 */
export async function readTake(name: string): Promise<Take> {
  const file = path.join(takeDir(name), 'take.json');

  let raw: string;
  try {
    raw = await readFile(file, 'utf8');
  } catch {
    throw new Error(
      `No take called "${name}". Nothing to compose from.\n\n` +
        `  npm run package && npm run record -- --grep ${name}\n\n` +
        'A take is the captured frames. It is not tracked, so it has to be ' +
        'recorded on this machine at least once.',
    );
  }

  const take = JSON.parse(raw) as Take;
  if (take.sequences.length === 0) {
    throw new Error(`The take "${name}" holds no sequences. Record it again.`);
  }
  return take;
}

/** Find a sequence, and list what does exist when the id is wrong. */
export function sequenceById(take: Take, id: string): Sequence {
  const found = take.sequences.find((sequence) => sequence.id === id);
  if (found) return found;

  throw new Error(
    `The take "${take.name}" has no sequence called "${id}". It has: ` +
      `${take.sequences.map((sequence) => sequence.id).join(', ')}.`,
  );
}

/**
 * The wall clock instant a mark names.
 *
 * `start` and `end` are accepted as well as a label, so an edit can say "play
 * from the beginning" without a mark having been declared for it.
 */
export function markTime(sequence: Sequence, label: string): number {
  if (label === 'start') return sequence.startedAt;
  if (label === 'end') return sequence.endedAt;

  const found = sequence.marks.find((mark) => mark.label === label);
  if (found) return found.at;

  const known = sequence.marks.map((mark) => mark.label);
  throw new Error(
    `The sequence "${sequence.id}" has no mark called "${label}". ` +
      (known.length > 0
        ? `It has: ${known.join(', ')}.`
        : 'It has no marks. Call mark() inside its drive to add one.'),
  );
}
