/**
 * check-deps.ts — what `bun run deps:check` runs. dependency-cruiser, plus a
 * ratchet on circular dependencies that can only be released downward.
 *
 *   bun run deps:check            # the gate (check:deep + ci.yml run this)
 *   bun run deps:check --list     # inventory: the cycles, grouped
 *   bun run deps:check --update   # re-record the set after fixing cycles
 *
 * ─── Why a wrapper at all ────────────────────────────────────────────────────
 * `no-circular` was `warn`, and depcruise exits 0 when only `warn` rules match.
 * So the rule matched 64 edges, printed them, and could not fail anything. The
 * count was then hand-typed into docs/commands.md and ci.yml, where nothing
 * checked it. That is the failure mode: a claim asserted in prose with no
 * mechanism behind it. The rule is now `error` in `.dependency-cruiser.cjs` —
 * a cycle IS a defect — and the standing backlog is held here, as data this
 * script verifies in both directions on every run.
 *
 * ─── Why the baseline lives in this file ─────────────────────────────────────
 * `find-casts.ts` keeps its justifications in the code being judged, because an
 * external list drifts from what it describes. A cycle has no single home to
 * annotate — it is a property of an edge set spanning 16 modules here — and
 * `src/**` cannot carry a marker for it. The nearest equivalent is to keep the
 * record in the gate that reads it: one file, generated, never hand-typed, and
 * impossible to have without the check that enforces it. It cannot drift the way
 * the "47" in docs/commands.md drifted, because a stale entry here is a build
 * failure (see "Removals fail too" below).
 *
 * ─── Why the SET of edges, and not a count, and not the cycles ───────────────
 * A count lets one cycle be fixed while another is introduced. The set is
 * strictly more precise, but only if each entry has a stable identity, and the
 * obvious identity — the cycle as depcruise renders it — is not stable. Measured
 * on this repo by adding one import (`get-models.ts -> auth-controller.ts`, a
 * shortcut inside the big component) and diffing the reported cycles:
 *
 *   identity = the rendered cycle path   +29 entries, -28   (unusable)
 *   identity = the dependency edge        +1 entry,   -0    (what is used here)
 *
 * depcruise reports a cycle from one entry point with one witness path found by
 * DFS. Adding an edge anywhere inside a strongly connected component gives many
 * unrelated cycles a shorter witness, so a path-keyed set rewrites itself
 * wholesale for a one-line change. The edge is invariant.
 *
 * The edges come from `modules[].dependencies[].circular` in depcruise's JSON,
 * NOT from `summary.violations`. The violation list is deduplicated by cycle —
 * 64 flagged edges collapse to 47 reported violations — and which edge survives
 * dedup depends on traversal order, so a new cycle can be attributed to an
 * already-recorded edge and slip through. In the experiment above, the edge
 * actually added was not among the violations at all; the flags caught it. The
 * `circular` flag is per-edge and exact: it is set iff the edge's endpoints are
 * in the same strongly connected component, i.e. iff that import closes a cycle.
 * A new cycle therefore always flags at least its own new edge. That is what
 * makes the ratchet sound.
 *
 * ─── Removals fail too ───────────────────────────────────────────────────────
 * Fixing a cycle fails this check until the record is updated. Without that the
 * ratchet only has teeth in one direction: a fixed cycle could silently come
 * back later and still match the record. `--update` is the fix and the failure
 * message names it. `--update` refuses to record NEW edges — the mechanical path
 * is down-only. Adding to this list is a deliberate hand-edit, visible in review.
 *
 * When the list reaches zero, delete it and this ratchet with it; the `error`
 * severity in `.dependency-cruiser.cjs` is then the whole gate.
 */
import path from "node:path"

const ROOT = path.resolve(import.meta.dir, "..")
const CONFIG = path.join(ROOT, ".dependency-cruiser.cjs")
const CRUISE_PATHS = ["src", "tests"]

const argv = process.argv.slice(2)
const UPDATE = argv.includes("--update")
const LIST = argv.includes("--list")

// --- BEGIN KNOWN CYCLE EDGES — generated by `bun run deps:check --update` ---
const KNOWN_CYCLE_EDGES = [
  "src/lib/auth/auth-controller.ts -> src/lib/auth/copilot-online-retry.ts",
  "src/lib/auth/auth-controller.ts -> src/lib/auth/token.ts",
  "src/lib/auth/auth-controller.ts -> src/lib/errors/error.ts",
  "src/lib/auth/auth-controller.ts -> src/lib/platform/logger.ts",
  "src/lib/auth/auth-controller.ts -> src/lib/platform/utils.ts",
  "src/lib/auth/auth-controller.ts -> src/lib/runtime-state/state.ts",
  "src/lib/auth/auth-controller.ts -> src/services/github/get-device-code.ts",
  "src/lib/auth/auth-controller.ts -> src/services/github/get-user.ts",
  "src/lib/auth/auth-controller.ts -> src/services/github/poll-access-token.ts",
  "src/lib/auth/auth-controller.ts -> src/services/github/refresh-access-token.ts",
  "src/lib/auth/copilot-online-retry.ts -> src/lib/auth/token.ts",
  "src/lib/auth/copilot-online-retry.ts -> src/lib/errors/error.ts",
  "src/lib/auth/copilot-online-retry.ts -> src/lib/platform/logger.ts",
  "src/lib/auth/copilot-online-retry.ts -> src/lib/platform/utils.ts",
  "src/lib/auth/copilot-online-retry.ts -> src/lib/runtime-state/state.ts",
  "src/lib/auth/token.ts -> src/lib/auth/auth-controller.ts",
  "src/lib/auth/token.ts -> src/lib/config/api-config.ts",
  "src/lib/auth/token.ts -> src/lib/errors/error.ts",
  "src/lib/auth/token.ts -> src/lib/platform/logger.ts",
  "src/lib/auth/token.ts -> src/lib/runtime-state/state.ts",
  "src/lib/auth/token.ts -> src/services/github/get-copilot-token.ts",
  "src/lib/auth/token.ts -> src/services/github/get-device-code.ts",
  "src/lib/auth/token.ts -> src/services/github/get-user.ts",
  "src/lib/auth/token.ts -> src/services/github/poll-access-token.ts",
  "src/lib/config/api-config.ts -> src/lib/runtime-state/state.ts",
  "src/lib/config/config-schema.ts -> src/lib/config/config.ts",
  "src/lib/config/config.ts -> src/lib/config/config-schema.ts",
  "src/lib/errors/error.ts -> src/lib/auth/auth-controller.ts",
  "src/lib/errors/error.ts -> src/lib/errors/upstream-error-advice.ts",
  "src/lib/errors/error.ts -> src/lib/runtime-state/state.ts",
  "src/lib/errors/upstream-error-advice.ts -> src/services/copilot/get-models.ts",
  "src/lib/http/send-request.ts -> src/lib/config/api-config.ts",
  "src/lib/http/send-request.ts -> src/lib/errors/error.ts",
  "src/lib/http/send-request.ts -> src/lib/runtime-state/state.ts",
  "src/lib/platform/logger.ts -> src/lib/runtime-state/state.ts",
  "src/lib/platform/utils.ts -> src/lib/runtime-state/state.ts",
  "src/lib/runtime-state/state.ts -> src/services/copilot/get-models.ts",
  "src/services/copilot/agent-initiator.ts -> src/services/copilot/create-chat-completions.ts",
  "src/services/copilot/agent-initiator.ts -> src/services/copilot/create-responses.ts",
  "src/services/copilot/create-chat-completions.ts -> src/services/copilot/agent-initiator.ts",
  "src/services/copilot/create-chat-completions.ts -> src/services/copilot/upstream-request.ts",
  "src/services/copilot/create-responses.ts -> src/services/copilot/agent-initiator.ts",
  "src/services/copilot/create-responses.ts -> src/services/copilot/upstream-request.ts",
  "src/services/copilot/get-models.ts -> src/lib/config/api-config.ts",
  "src/services/copilot/get-models.ts -> src/lib/errors/error.ts",
  "src/services/copilot/get-models.ts -> src/lib/http/send-request.ts",
  "src/services/copilot/get-models.ts -> src/lib/runtime-state/state.ts",
  "src/services/copilot/upstream-request.ts -> src/services/copilot/agent-initiator.ts",
  "src/services/github/get-copilot-token.ts -> src/lib/config/api-config.ts",
  "src/services/github/get-copilot-token.ts -> src/lib/errors/error.ts",
  "src/services/github/get-copilot-token.ts -> src/lib/http/send-request.ts",
  "src/services/github/get-copilot-token.ts -> src/lib/runtime-state/state.ts",
  "src/services/github/get-device-code.ts -> src/lib/config/api-config.ts",
  "src/services/github/get-device-code.ts -> src/lib/http/send-request.ts",
  "src/services/github/get-user.ts -> src/lib/config/api-config.ts",
  "src/services/github/get-user.ts -> src/lib/http/send-request.ts",
  "src/services/github/get-user.ts -> src/lib/runtime-state/state.ts",
  "src/services/github/poll-access-token.ts -> src/lib/config/api-config.ts",
  "src/services/github/poll-access-token.ts -> src/lib/http/send-request.ts",
  "src/services/github/poll-access-token.ts -> src/lib/platform/utils.ts",
  "src/services/github/poll-access-token.ts -> src/services/github/get-device-code.ts",
  "src/services/github/refresh-access-token.ts -> src/lib/config/api-config.ts",
  "src/services/github/refresh-access-token.ts -> src/lib/http/send-request.ts",
  "src/services/github/refresh-access-token.ts -> src/services/github/poll-access-token.ts",
]
// --- END KNOWN CYCLE EDGES ---

interface CycleStep {
  name: string
}
interface Dependency {
  resolved: string
  circular?: boolean
  cycle?: CycleStep[]
}
interface CruisedModule {
  source: string
  dependencies: Dependency[]
}
interface Violation {
  from: string
  to: string
  rule: { name: string; severity: string }
}
interface CruiseResult {
  modules: CruisedModule[]
  summary: {
    violations: Violation[]
    totalCruised: number
    totalDependenciesCruised: number
  }
}

/** Run depcruise via its own entry point rather than the `.bin` shim, which is
 *  a `.cmd` on Windows and not spawnable the same way. */
async function cruise(): Promise<CruiseResult> {
  const entry = path.join(
    ROOT,
    "node_modules/dependency-cruiser/bin/dependency-cruise.mjs",
  )
  const proc = Bun.spawn(
    [
      process.execPath,
      entry,
      "--config",
      CONFIG,
      "--output-type",
      "json",
      ...CRUISE_PATHS,
    ],
    { cwd: ROOT, stdout: "pipe", stderr: "pipe" },
  )
  const [stdout, stderr] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
  ])
  await proc.exited
  // depcruise's exit code encodes violation counts, so it is not a usable
  // success signal here; parseable output of the expected shape is.
  try {
    const parsed: unknown = JSON.parse(stdout)
    const result = parsed as CruiseResult
    if (!Array.isArray(result.modules)) throw new Error("no `modules` array")
    return result
  } catch (error) {
    console.error("✖ dependency-cruiser did not produce a usable report.")
    if (stderr.trim()) console.error(stderr.trim())
    console.error(String(error))
    process.exit(1)
  }
}

const edgeId = (from: string, to: string): string => `${from} -> ${to}`

/** Every dependency edge whose endpoints share a strongly connected component,
 *  i.e. every import that closes a cycle. Deduplicated: a module can declare the
 *  same target twice (a value import and a type-only one). */
function cycleEdges(result: CruiseResult): Map<string, string[]> {
  const edges = new Map<string, string[]>()
  for (const module of result.modules) {
    for (const dep of module.dependencies) {
      if (!dep.circular) continue
      const id = edgeId(module.source, dep.resolved)
      if (edges.has(id)) continue
      // `cycle` is one witness path back to `module.source`; it is context for a
      // failure message, never part of the identity (see the header).
      edges.set(id, [module.source, ...(dep.cycle ?? []).map((s) => s.name)])
    }
  }
  return edges
}

/** Group modules into connected components over the cycle edges. Two modules are
 *  connected by cycle edges iff they are in the same strongly connected
 *  component, so this is the SCC partition. */
function components(ids: string[]): string[][] {
  const parent = new Map<string, string>()
  const find = (x: string): string => {
    let root = parent.get(x) ?? x
    while (root !== (parent.get(root) ?? root)) root = parent.get(root) ?? root
    parent.set(x, root)
    return root
  }
  const union = (a: string, b: string): void => {
    const [ra, rb] = [find(a), find(b)]
    if (ra !== rb) parent.set(ra, rb)
  }
  for (const id of ids) {
    const [from, to] = id.split(" -> ")
    if (!from || !to) continue
    parent.set(from, parent.get(from) ?? from)
    parent.set(to, parent.get(to) ?? to)
    union(from, to)
  }
  const groups = new Map<string, string[]>()
  for (const node of parent.keys()) {
    const root = find(node)
    groups.set(root, [...(groups.get(root) ?? []), node])
  }
  return [...groups.values()]
    .map((g) => g.sort())
    .sort((a, b) => b.length - a.length || (a[0] ?? "").localeCompare(b[0] ?? ""))
}

async function writeKnown(edges: string[]): Promise<void> {
  const self = import.meta.path
  const source = await Bun.file(self).text()
  const body = edges.map((edge) => `  ${JSON.stringify(edge)},`).join("\n")
  const next = source.replace(
    /(\/\/ --- BEGIN KNOWN CYCLE EDGES[^\n]*\nconst KNOWN_CYCLE_EDGES = \[\n)[\s\S]*?(\n\]\n\/\/ --- END KNOWN CYCLE EDGES ---)/,
    (_match, head: string, tail: string) => `${head}${body}${tail}`,
  )
  if (next === source) {
    console.error("✖ could not locate the generated block in check-deps.ts.")
    process.exit(1)
  }
  await Bun.write(self, next)
}

const result = await cruise()
const edges = cycleEdges(result)
const current = [...edges.keys()].sort()
const known = new Set(KNOWN_CYCLE_EDGES)
const added = current.filter((edge) => !known.has(edge))
const gone = KNOWN_CYCLE_EDGES.filter((edge) => !edges.has(edge))

if (LIST) {
  const groups = components(current)
  console.log(
    `${current.length} cycle edge(s) over ${groups.reduce((n, g) => n + g.length, 0)} module(s), in ${groups.length} strongly connected component(s):\n`,
  )
  for (const [index, group] of groups.entries()) {
    const inGroup = current.filter((edge) =>
      group.includes(edge.split(" -> ")[0] ?? ""),
    )
    console.log(`#${index + 1} — ${group.length} modules, ${inGroup.length} edges`)
    for (const module of group) console.log(`     ${module}`)
    console.log("")
  }
  process.exit(0)
}

// The two `error` rules (not-to-test, no-route-imports-from-lib-or-services) are
// absolute; only `no-circular` is ratcheted.
const other = result.summary.violations.filter((v) => v.rule.name !== "no-circular")
const errors = other.filter((v) => v.rule.severity === "error")
for (const v of other.filter((v) => v.rule.severity !== "error")) {
  console.log(`warn  ${v.rule.name}: ${v.from} -> ${v.to}`)
}
for (const v of errors) {
  console.error(`✖ ${v.rule.name}: ${v.from} -> ${v.to}`)
}

if (UPDATE) {
  if (added.length > 0) {
    console.error(
      `\n✖ --update refuses to record ${added.length} NEW cycle edge(s). The ratchet\n` +
        `  only releases downward; remove the import instead:`,
    )
    for (const edge of added) console.error(`  + ${edge}`)
    process.exit(1)
  }
  await writeKnown(current)
  console.log(
    gone.length > 0 ?
      `\n✓ recorded ${current.length} cycle edge(s) — ${gone.length} fewer than before.`
    : `\n✓ recorded ${current.length} cycle edge(s) — no change.`,
  )
  process.exit(errors.length > 0 ? 1 : 0)
}

let failed = errors.length > 0

if (added.length > 0) {
  failed = true
  console.error(
    `\n✖ ${added.length} NEW circular dependenc${added.length === 1 ? "y" : "ies"} — this import closes a cycle:`,
  )
  // One bad import into a large component can flag dozens of edges at once;
  // print enough to act on rather than a screenful of CI log.
  for (const edge of added.slice(0, 12)) {
    console.error(`\n  ${edge}`)
    const witness = edges.get(edge) ?? []
    if (witness.length > 1) console.error(`    cycle: ${witness.join(" → ")}`)
  }
  if (added.length > 12) {
    console.error(`\n  … and ${added.length - 12} more (bun run deps:check --list).`)
  }
  console.error(
    `\nBreak the cycle (extract the shared type or helper into a module both can\n` +
      `import). The recorded set may only shrink — see scripts/check-deps.ts.`,
  )
}

if (gone.length > 0) {
  failed = true
  console.error(
    `\n✖ ${gone.length} recorded cycle edge(s) no longer exist. The ratchet has to be\n` +
      `  tightened in the same change that loosens the graph, or the cycle can come\n` +
      `  back later and still match the record:`,
  )
  for (const edge of gone) console.error(`  - ${edge}`)
  console.error(`\nRun: bun run deps:check --update`)
}

if (failed) process.exit(1)

console.log(
  `✓ ${result.summary.totalCruised} modules, ${result.summary.totalDependenciesCruised} dependencies, ` +
    `0 layering violations.`,
)
console.log(
  `  ${current.length} circular import(s) recorded and unchanged ` +
    `(bun run deps:check --list).`,
)
