#!/usr/bin/env bun
/**
 * The whole manual release sequence, so the tree it leaves behind is correct
 * without a human remembering a step.
 *
 * IT IS TWO PHASES, AND THE SPLIT IS FORCED BY A RULESET. `main-require-pr` now
 * carries `bypass_actors: []` — nothing reaches `main` outside a pull request,
 * permanently. The single `release:manual` this replaces ended in `bumpp`, which
 * commits, tags AND pushes STRAIGHT TO `main`; that push is now rejected, and
 * rejected AFTER the bump, the changelog write and the local tag, i.e. on the
 * irreversible side of the flow. So:
 *
 *   release:prepare vX.Y.Z   guard, pin, gate 4, gate 5, changelog, bump,
 *                            rebuild, commit on `release/vX.Y.Z`, push the
 *                            BRANCH, open the PR. CUTS NO TAG.
 *   release:tag vX.Y.Z       once that PR has merged: fetch, assert the merged
 *                            manifest reads X.Y.Z and that the tip IS the
 *                            release commit, on the tree you are standing on,
 *                            re-run gate 4, cut the ANNOTATED tag on the merged
 *                            HEAD, push it.
 *
 * THE TAG CANNOT BE CUT IN PHASE A, and that is what makes this two commands
 * rather than one flag. A squash merge rewrites the SHA, so a tag created on the
 * branch would point at a commit that never reaches `main`. It has to be created
 * after the merge, against `main`'s actual merged HEAD — which is what every one
 * of phase B's assertions is about. Only the release COMMIT ever needed the
 * bypass: both rulesets are `target: branch` and there is no tag ruleset, so
 * `git push origin vX.Y.Z` is unrestricted.
 *
 * THIS IS A STRENGTHENING, NOT A WORKAROUND. Under the direct-push flow the
 * release commit was the ONE commit that reached `main` completely unverified —
 * the bump, the regenerated `dist/` and the generated changelog all landed with
 * no check run against them. It now passes `test`, `windows` and `gate` like
 * every other commit, and `bindings:check` inside `test` is precisely the gate
 * that catches the stale `dist/` this file was written for.
 *
 * PUBLISHING IS `publish-package.yml`, which fires on the tag phase B pushes and
 * runs `bun publish` against the GitHub Package Registry. CI pins the Bun
 * version by construction, so the tarball cannot be built by whatever the
 * releaser happens to have on PATH — and that is why `--no-publish` is a no-op
 * rather than a switch (see `NO_PUBLISH_FLAG`). `prepack.ts` still guards the
 * pin, both for that workflow and for anyone running `bun publish` or
 * `bun pm pack` by hand.
 *
 * `release:manual` was `release:preflight && bumpp && bun publish --access
 * public`. Two things were missing from it, and they turn out to be the same
 * thing twice:
 *
 *   1. `bun build` INLINES `package.json` (`BUILD_VERSION` in
 *      `src/lib/update/build-info.ts` falls back to `packageJson.version`), and
 *      `bumpp` bumps that version. So every release left the COMMITTED
 *      `dist/main.js` describing the previous version and `bindings:check` red
 *      on `main` until someone regenerated by hand. Measured, same Bun 1.3.11,
 *      one bumped version: `85697a48…` at `0.3.2` vs `2e541596…` at `0.3.3`.
 *      v0.3.2 and v0.4.0 were both rebuilt by hand after the fact.
 *   2. Nothing asserted a clean working tree, so an unrelated in-flight edit
 *      could be swept into the release commit and shipped under the tag.
 *
 * A third thing was missing, and it is the same thing a third time: the
 * CHANGELOG entry. The runbook used to say "generate the block with
 * `release:notes vX.Y.Z` and paste it into `CHANGELOG.md`" and then, in the very
 * next step, "run `release:manual`" — whose FIRST action is the clean-tree guard
 * above, which refuses any tracked modification, the freshly pasted changelog
 * included. Step 3 guaranteed step 4 would refuse. v0.4.1 was cut around it by
 * committing the changelog separately first, which is why its history carries
 * two commits where every release before it carries one. So this file writes the
 * entry itself: the tag is an argument to it, `release-notes.ts` is a sibling,
 * and `CHANGELOG.md` carries an insertion anchor put there for exactly this.
 * The guard keeps its zero exemptions — see WHERE THE CHANGELOG IS WRITTEN.
 *
 * WHY A WRAPPER RATHER THAN JUST `bumpp -x`. `bumpp`'s execute hook is the right
 * PLACE for the rebuild — it runs after `updateFiles` and before `gitCommit`
 * (`versionBump()` in `bumpp/dist/shared/*.mjs`), which is the only window where
 * the new version is on disk and the commit has not happened yet. But `-x` alone
 * is not sufficient, because of how `bumpp` commits. Its default `gitCommit` is:
 *
 *     git commit --allow-empty --message <msg> <the files bumpp itself updated>
 *
 * That is git's PATHSPEC form, and `git commit <pathspec>` deliberately IGNORES
 * THE INDEX for every other path. So a hook that does the documented fix —
 * `git add -f dist/main.js` — has its work silently dropped from the release
 * commit and left dangling after it, which is the exact state this file exists
 * to prevent. Measured on a throwaway repo, staging `dist/main.js` and then
 * committing `bumpp`-style:
 *
 *     A: git commit -m … package.json     → git show HEAD:dist/main.js = v1  (stale)
 *                                           git status              = `M  dist/main.js`
 *     B: git commit -m … --all            → git show HEAD:dist/main.js = v2  (correct)
 *                                           git status              = clean
 *
 * `--all` is what makes `bumpp` commit the INDEX rather than a pathspec, so the
 * hook's `git add -f` lands. (`-a` stages tracked modifications ON TOP OF the
 * index; anything already added — including a brand-new content-hash chunk that
 * `-a` would never have picked up on its own — stays.)
 *
 * AND `--all` IS EXACTLY WHAT DISABLES `bumpp`'S OWN CLEAN-TREE CHECK. From its
 * CLI:
 *
 *     if (!options.all && !options.noGitCheck) await checkGitStatus()
 *
 * — and `noGitCheck` defaults to `true` regardless, so `bumpp` checks nothing
 * today and would check nothing under the flag the rebuild needs. The rebuild
 * fix and the clean-tree guard are therefore not two independent chores: turning
 * on the first removes the only backstop that could have supplied the second.
 * Something has to own the ordering — guard, then pin, then bump, then tag —
 * and a `&&` chain in `package.json` cannot express "guard the tree that the
 * step after next is allowed to modify". Hence this file.
 *
 * WHAT COUNTS AS CLEAN, AND WHY (see `cleanTreeObjection`). Blocking: every
 * TRACKED modification, staged or unstaged, including `dist/`. Non-blocking:
 * untracked files.
 *
 *   - Tracked, including `dist/`: `git commit --all` sweeps every tracked
 *     modification into the release commit, so those bytes ship under the tag
 *     with no gate having seen them. `dist/` is force-tracked against
 *     `.gitignore`, so a hand-edited or half-built `dist/` is a tracked
 *     modification like any other — and `bindings:check` reads the INDEX, not
 *     the working tree, so it is structurally blind to it. This guard is the
 *     only thing in the repo that looks.
 *   - It does not fight the rebuild, because of WHERE it runs: the guard is step
 *     one of this file, and the rebuild happens later, inside `bumpp`'s execute
 *     hook. By the time `dist/` is touched the guard has already passed. The
 *     guard's demand is "`dist/` matched `HEAD` when we started", which is true
 *     of every tree the previous release left behind.
 *   - Untracked files do NOT block. The mechanism being guarded is `git commit
 *     --all`, which stages only tracked paths; an untracked file cannot reach
 *     the release commit by any route in this flow. Blocking on one would fail
 *     the release for a scratch note or an editor artifact — a false positive on
 *     a path whose next step is irreversible. They are listed as a note instead,
 *     so a releaser who expected a file to ship finds out before the tag rather
 *     than after. (Ignored files are not listed by `git status --porcelain` at
 *     all, so nothing under an untouched `dist/` shows up here.)
 *
 * WHY THE TAG IS AN ARGUMENT (`release:prepare vX.Y.Z`). The changelog block
 * is generated from the GitHub milestone whose title IS the tag, so the notes
 * cannot be fetched — and a bad milestone cannot be refused — until the version
 * is known. Letting `bumpp` prompt for it would push both after the bump. The
 * milestone model already decides the tag in advance (`release:check milestone
 * vX.Y.Z`, `release:notes vX.Y.Z`), so naming it once more here takes nothing
 * away, and the version reaches `bumpp` as `--release X.Y.Z`, which makes gate 3
 * — "the tag matches `package.json`" — true by construction rather than by a
 * preflight anyone can skip. That is the failure `v0.1.1` shipped.
 *
 * WHERE THE CHANGELOG IS WRITTEN, AND WHY IT IS NOT AN EXEMPTION. The block is
 * FETCHED, VALIDATED AND RENDERED before `bumpp` — so a milestone that
 * `release:notes` would refuse to emit for (missing, empty, an unparseable PR
 * title, an unmerged PR) refuses the whole release at exit 1, with the tree
 * still exactly as the guard found it. It is WRITTEN inside `bumpp`'s execute
 * hook, beside the rebuild, for the same reason the rebuild is there: that is
 * the only window where the commit has not happened yet, and `git commit --all`
 * is about to sweep the working tree into it. The hook therefore produces
 * everything the release commit carries beyond the version bump itself.
 *
 * Two consequences worth stating, because both are the point:
 *
 *   - The guard is untouched and still has NO exemptions. `CHANGELOG.md` is
 *     dirty for the same reason `dist/` is: this script dirtied it, after the
 *     guard, deliberately. The guard only ever asked "did the tree match HEAD
 *     when we started".
 *   - Nothing is written on any refusal path, and nothing is written before the
 *     `bumpp` confirmation prompt. Declining that prompt (`process.exit(1)` in
 *     `bumpp`'s CLI) or hitting Ctrl-C leaves the tree clean, so the next
 *     attempt is not blocked by the leftovers of the last one — which is the
 *     failure mode of pasting the block by hand, mechanised.
 *
 * The rendered block reaches the hook through the environment
 * (`MAXIMAL_RELEASE_CHANGELOG_BLOCK`), because the hook is a separate process
 * `bumpp` spawns with the ambient environment. A temp file would work too and
 * costs an untracked artefact in the one flow that reports untracked files. With
 * the variable unset — a by-hand `release.ts --rebuild` — the hook rebuilds and
 * stages `dist/` and touches no markdown, exactly as it did before.
 *
 * THAT HANDOVER DEPENDS ON `realRunner` PASSING `env` EXPLICITLY, and it did not
 * until this change. Bun's `spawnSync` defaults the child's environment to the
 * SNAPSHOT the process started with, not to the current `process.env`, so a
 * variable set at runtime is dropped without a word. Measured, Bun 1.3.11:
 *
 *     process.env.PROBE = "set-by-parent"
 *     spawnSync(bun, ["-e", …])                        → PROBE undefined
 *     spawnSync(bun, ["-e", …], { env: process.env })  → PROBE set-by-parent
 *
 * Caught in a scratch clone, where the first end-to-end release came out green
 * with no changelog entry in the commit. `prepack.ts`'s `realRunner` now names
 * `env`, and `prepack.test.ts` pins it — it is the one test in that suite that
 * spawns anything, because the failure it prevents is silent and green.
 *
 * AN ENTRY THAT IS ALREADY THERE IS LEFT ALONE. If `CHANGELOG.md` already has a
 * `## X.Y.Z` heading for the version being cut — a re-run, or a human who pasted
 * it — the changelog step is skipped in full, including the `gh` reads. It is
 * reported, not refused: the entry the release needs exists, and rewriting
 * somebody's hand-edited block (or appending a second one) is the only outcome
 * worse than leaving it.
 *
 * THE REBUILD USES `process.execPath`, NEVER A BARE `bun` — the trap
 * `scripts/ops/prepack.ts` documents, re-measured for the `bun run` path this
 * script is launched through:
 *
 *     $ ~/.bun/bin/bun run probe        # outer interpreter: 1.3.11, the pin
 *     execPath      : /opt/homebrew/Cellar/bun/1.3.10/bin/bun
 *     versions.bun  : 1.3.14
 *
 * i.e. invoking the pinned binary and letting the script say `bun` gets you the
 * developer's Bun, and `bun build`'s output is a function of the Bun version. So
 * the rebuild goes through `prepack()`, which bundles with `process.execPath` —
 * the same binary whose `process.versions.bun` was checked, with no PATH lookup
 * in between. For the same reason the execute hook is spawned as
 * `"<process.execPath>" "<this file>" --rebuild` rather than `bun run …`:
 * `bumpp` spawns it with the ambient PATH, so naming the binary is the only way
 * to know which one bundles.
 *
 * THE PIN ASSERTION STILL MEASURES THE RIGHT PROCESS. `release:preflight`'s
 * guarantee was that it is launched by the same bare `bun` that `prepack` will
 * later get; this file is launched the same way (`bun run release:prepare`), so
 * asserting on its own `process.versions.bun` is the identical measurement. It
 * delegates to `prepack({ checkOnly: true })` so the refusal text stays in one
 * place. Phase B does not re-assert it: it builds nothing, and the bytes it
 * tags were built by phase A and re-verified by `bindings:check` on the PR.
 *
 * WHAT IS STAGED comes from `check-bindings.ts`'s `ARTIFACTS`, not a literal
 * list, so the set this stages cannot drift from the set `bindings:check`
 * verifies. `-f` is not optional: `dist/` is gitignored, so a bare `git add`
 * silently skips a NEW file (a renamed content-hash chunk).
 *
 * Usage:
 *   bun run release:prepare vX.Y.Z    # guard, pin, gates, notes, bump+rebuild,
 *                                     #   branch, push, PR — no tag
 *   bun run release:prepare vX.Y.Z -y # anything else goes to bumpp
 *   bun run release:tag vX.Y.Z        # after that PR merges: tag main, push it
 *   bun scripts/ops/release.ts --rebuild   # just rebuild + stage dist/
 *
 * Exit codes: 0 ok · 1 refused · 2 a step failed, including a gate that could
 * not READ what it compares against. Phase A refuses on no tag, a dirty tree, an
 * off-pin Bun, a tag that already exists or is not ahead of every tag that does,
 * a PR still open in the milestone being cut, a milestone the notes cannot be
 * generated from, or a `release/vX.Y.Z` branch that is already there. Phase B
 * refuses on a merged manifest that is not X.Y.Z, a merged head that is not the
 * release commit itself, a checkout that is not standing on that merged commit
 * with a clean tree, or gate 4. Every phase-A refusal is ahead of the branch and
 * `bumpp`; every phase-B refusal is ahead of `git tag`.
 *
 * TWO OF THOSE REFUSALS ARE `release-gates.ts`, CALLED FROM HERE. Gate 4 (the
 * tag is ahead of every tag that exists, local AND remote) and gate 5 (nothing
 * that claims to ship in this release is still open) are both checks about the
 * instant the tag is cut, so a preflight a human runs and a workflow that fires
 * on tag push are respectively skippable and too late. Gate 4 therefore runs in
 * BOTH phases: cheap early refusal in `prepare()`, and again in `tagRelease()`
 * because the PR may have sat open long enough for another agent to push the tag
 * this one is about. See `evaluateTagOrder` and `evaluateOpenPrs`.
 *
 * `git` and every child process go through the two injectable runners this repo
 * already uses (`check-bindings.ts`'s `GitRunner`, `prepack.ts`'s
 * `CommandRunner`), the GitHub reads go through `release-notes.ts`'s `GhRunner`,
 * and `CHANGELOG.md` is read and written through an injected pair — so the tests
 * run offline without a bundler, a repository, a registry or a working copy.
 */

import fs from "node:fs"
import path from "node:path"

import { ARTIFACTS, type GitRunner, realGit } from "./check-bindings"
import { type CommandRunner, prepack, type PrepackOptions, realRunner } from "./prepack"
import {
  collectOpenPrGate,
  collectTagOrderGate,
  DEFAULT_REMOTE,
  exitCodeFor as gateExitCodeFor,
  type GateReport,
  renderFindings,
} from "./release-gates"
import {
  collectReleaseNotes,
  exitCodeFor,
  type GhRunner,
  realGh,
  type ReleaseNotes,
  renderChangelog,
  renderProblems,
  stripV,
} from "./release-notes"

// Every child process — `git`, `gh`, `bumpp` — runs through the three runners
// imported above, all of which already resolve the repo root from their own
// file, so this script works from any cwd without repeating it.
// `CHANGELOG.md` is the one path this file resolves itself.
const REPO_ROOT = path.resolve(import.meta.dir, "..", "..")

/** Runs only the rebuild-and-stage step. What `bumpp`'s execute hook invokes. */
export const REBUILD_FLAG = "--rebuild"

/**
 * ACCEPTED AND IGNORED. This script used to end in `bun publish` and this flag
 * skipped it; `publish-package.yml` owns publishing now, so there is nothing
 * left to skip and every invocation behaves as if the flag were passed. It is
 * still PARSED, and still kept out of `bumpp`'s argv, so the invocation in
 * everyone's shell history keeps working instead of erroring — and so `bumpp`
 * never sees a `--no-publish` it would read as its own.
 */
export const NO_PUBLISH_FLAG = "--no-publish"

/** This script's own flags, which must never be forwarded to `bumpp`. */
export const OWN_FLAGS: ReadonlyArray<string> = [REBUILD_FLAG, NO_PUBLISH_FLAG]

/** The two phases. Named, because doing the wrong one silently is the hazard. */
export const SUBCOMMANDS = ["prepare", "tag"] as const

export type Subcommand = (typeof SUBCOMMANDS)[number]

/** The tag this release cuts. Prereleases are not modelled anywhere in this tooling. */
export const TAG_RE = /^v\d+\.\d+\.\d+$/u

/** The branch the PR merges into, and the ref phase B tags. */
export const DEFAULT_BASE = "main"

/**
 * Where phase A lands the release commit. Phase B never looks at it: by then the
 * squash merge has rewritten the SHA and the branch is a dead end, which is the
 * entire reason the tag is not cut in phase A.
 */
export function releaseBranch(tag: string): string {
  return `release/${tag}`
}

/**
 * The release commit's subject, the release PR's title, and the tag's annotation
 * — one string, used three times, because gate 5 keys off it.
 *
 * `release-gates.ts` exempts a PR whose TITLE matches `RELEASE_COMMIT_RE` from
 * every gate, gate 5 included. Without that, the release PR is a PR open in the
 * milestone being cut, and a re-run of phase A — the case where `CHANGELOG.md`
 * already documents the version, so the changelog step is skipped and gate 5 is
 * the only thing still reading GitHub — would refuse the release on its own
 * pull request. The signal is the title rather than the branch name because the
 * title is what squash-merge turns into the commit subject and what every other
 * gate already reads; a branch name is a convention nothing verifies.
 *
 * `bumpp`'s default commit message is `chore: release v` + the new version, so
 * the commit this returns a subject for is the commit `bumpp` makes, byte for
 * byte, without configuring anything. `release.test.ts` pins the string against
 * `RELEASE_COMMIT_RE` itself, so the two cannot drift apart in prose.
 */
export function releaseCommitSubject(tag: string): string {
  return `chore: release ${tag}`
}

/**
 * The release PR's body. Short on purpose: everything it could explain is in the
 * runbook, and the one thing a reviewer cannot derive from the diff is that a
 * second command is still owed after the merge.
 */
export function releasePrBody(tag: string): string {
  return (
    `Prepared by \`bun run release:prepare ${tag}\`.\n`
    + `\n`
    + `- \`package.json\` bumped to ${stripV(tag)}\n`
    + `- \`CHANGELOG.md\` entry generated from milestone \`${tag}\`\n`
    + `- \`${stagePathspecs().join("`, `")}\` rebuilt on the pinned Bun and committed\n`
    + `\n`
    + `**The tag is not cut yet.** Merge this, then run \`bun run release:tag ${tag}\`:\n`
    + `the squash rewrites this branch's SHA, so the tag can only be created on\n`
    + `\`${DEFAULT_BASE}\`'s merged HEAD. That push is what fires \`release-tag-check.yml\`\n`
    + `and \`publish-package.yml\`.\n`
  )
}

// --- the changelog ---

/** The file the generated block is inserted into. */
export const CHANGELOG_FILE = "CHANGELOG.md"

/**
 * The insertion point. `CHANGELOG.md` carries this comment so automation never
 * has to guess an offset into a file whose preamble is prose. Matched by prefix,
 * not by its full text, so the sentence after it stays editable.
 */
export const CHANGELOG_ANCHOR = /^<!-- releases below.*$/mu

/**
 * How the rendered block reaches `bumpp`'s execute hook, which is a separate
 * process spawned with the ambient environment. Unset means "rebuild only",
 * which is what a by-hand `release.ts --rebuild` gets.
 */
export const CHANGELOG_ENV = "MAXIMAL_RELEASE_CHANGELOG_BLOCK"

/**
 * Does the file already document this version? Both heading shapes
 * `release-notes.ts` can emit count: `## [0.4.2](compare-link) (date)` and the
 * unlinked `## 0.4.2 (date)` a first release gets.
 */
export function changelogHasVersion(source: string, version: string): boolean {
  const escaped = version.replaceAll(".", "\\.")
  return new RegExp(`^## (?:\\[${escaped}\\]|${escaped}[ (])`, "mu").test(source)
}

/**
 * Insert `block` directly below the anchor, or `undefined` when the anchor is
 * gone. One blank line separates it from the release under it, which is the
 * spacing every existing pair in the file already uses — so the diff of a
 * generated insert is indistinguishable from the pasted ones above it.
 */
export function insertChangelogBlock(source: string, block: string): string | undefined {
  const match = CHANGELOG_ANCHOR.exec(source)
  if (!match) return undefined
  const at = match.index + match[0].length
  const head = source.slice(0, at)
  const tail = source.slice(at)
  const entry = block.trimEnd()
  if (tail.trim() === "") return `${head}\n\n${entry}\n`
  return `${head}\n\n${entry}${tail.replace(/^\n*/u, "\n\n")}`
}

/** Read/write seam for `CHANGELOG.md`, so no test needs a working copy. */
export interface ChangelogIo {
  read?: () => string
  write?: (contents: string) => void
}

function readChangelog(io: ChangelogIo): () => string {
  return io.read ?? (() => fs.readFileSync(path.join(REPO_ROOT, CHANGELOG_FILE), "utf8"))
}

function anchorObjection(): string {
  return (
    `release: REFUSING — ${CHANGELOG_FILE} has no insertion anchor.\n`
    + `\n`
    + `  Expected a line beginning \`<!-- releases below\`, which is what tells this\n`
    + `  script where a generated block goes without guessing an offset.\n`
    + `\n`
    + `Put the anchor back above the newest release heading, or paste the block by\n`
    + `hand and re-run — an entry that is already there is left alone:\n`
    + `    bun run release:notes <tag>\n`
  )
}

/** What the changelog step decided. Exactly one of these three fields is set. */
export interface ChangelogPlan {
  /** The block to insert, when there is one to insert. */
  block?: string
  /** Why the release must not proceed. */
  objection?: string
  /** Why there is nothing to do, when that is the answer. */
  note?: string
}

export interface ChangelogPlanOptions extends ChangelogIo {
  tag: string
  gh?: GhRunner
  now?: () => Date
}

/**
 * Fetch, validate and render the entry for `tag` — everything about the
 * changelog that can fail, done BEFORE `bumpp` so a failure costs nothing.
 *
 * The refusal condition is `release:notes`'s own: this returns an objection for
 * anything that would make it exit non-zero and write nothing. A release whose
 * notes cannot be trusted is a release that must not be cut, and there is
 * deliberately no `--force` here — `release:notes --force` emits the well-formed
 * subset for a human to paste, which this step then finds and leaves alone.
 */
export function planChangelog(options: ChangelogPlanOptions): ChangelogPlan {
  let source: string
  try {
    source = readChangelog(options)()
  } catch (err) {
    return { objection: `release: could not read ${CHANGELOG_FILE} — ${err instanceof Error ? err.message : String(err)}` }
  }
  if (!CHANGELOG_ANCHOR.test(source)) return { objection: anchorObjection() }

  const version = stripV(options.tag)
  if (changelogHasVersion(source, version)) {
    return { note: `release: ${CHANGELOG_FILE} already documents ${version} — leaving it exactly as it is.` }
  }

  let notes: ReleaseNotes
  try {
    notes = collectReleaseNotes({ tag: options.tag, gh: options.gh, now: options.now })
  } catch (err) {
    return {
      objection:
        `release: REFUSING — could not generate the ${CHANGELOG_FILE} entry for ${options.tag}.\n`
        + `\n  ${err instanceof Error ? err.message : String(err)}\n`,
    }
  }

  if (exitCodeFor(notes) !== 0) {
    return {
      objection:
        `${renderProblems(notes.problems)}\n`
        + `\n`
        + `release: REFUSING — the milestone \`${options.tag}\` cannot produce trustworthy\n`
        + `notes, and the entry is the only thing that reaches the changelog. Fix the\n`
        + `milestone, or paste a block by hand and re-run:\n`
        + `    bun run release:notes ${options.tag} --force\n`,
    }
  }
  return { block: renderChangelog(notes) }
}

/**
 * Write the block into `CHANGELOG.md`. Runs INSIDE `bumpp`, between the bump and
 * the commit, so `git commit --all` picks it up. Returns an objection or
 * `undefined`; everything that could realistically fail here was already checked
 * by `planChangelog` before the bump.
 */
export function applyChangelog(block: string, io: ChangelogIo = {}): string | undefined {
  const write = io.write ?? ((contents: string) => { fs.writeFileSync(path.join(REPO_ROOT, CHANGELOG_FILE), contents) })
  let source: string
  try {
    source = readChangelog(io)()
  } catch (err) {
    return `release: could not read ${CHANGELOG_FILE} — ${err instanceof Error ? err.message : String(err)}`
  }
  const next = insertChangelogBlock(source, block)
  if (next === undefined) return anchorObjection()
  try {
    write(next)
  } catch (err) {
    return `release: could not write ${CHANGELOG_FILE} — ${err instanceof Error ? err.message : String(err)}`
  }
  return undefined
}

// --- what gets staged ---

/**
 * The committed, generated paths the release commit must carry — read from the
 * gate that verifies them, so the two cannot disagree. `dist/lib`, `dist/main.js`.
 */
export function stagePathspecs(artifacts: ReadonlyArray<{ id: string }> = ARTIFACTS): Array<string> {
  return artifacts.map((artifact) => artifact.id)
}

/** `-f` because `dist/` is gitignored and a bare `git add` skips new files there. */
export function stageArgv(pathspecs: ReadonlyArray<string> = stagePathspecs()): Array<string> {
  return ["add", "-f", "--", ...pathspecs]
}

// --- the clean-tree guard ---

/** One `git status --porcelain` record, split into its status code and its path. */
export interface StatusRecord {
  /** The two-character XY code. `??` is untracked. */
  code: string
  path: string
}

/**
 * Parse `git status --porcelain` (v1). Paths containing a newline are quoted by
 * git in this format, so splitting on newlines cannot cut a record in half.
 */
export function parseStatus(porcelain: string): Array<StatusRecord> {
  const records: Array<StatusRecord> = []
  for (const line of porcelain.split("\n")) {
    if (line.length < 4) continue
    records.push({ code: line.slice(0, 2), path: line.slice(3) })
  }
  return records
}

/** Untracked, and therefore unreachable by `git commit --all`. */
function isUntracked(record: StatusRecord): boolean {
  return record.code === "??"
}

/** Phase A's consequence: `--all` ships them under the tag, reviewed by nobody. */
export const SWEPT_INTO_THE_COMMIT =
  `The release commit is made with \`git commit --all\` so that the regenerated\n`
  + `dist/ lands inside it, which means every tracked modification above would be\n`
  + `swept in and shipped under the tag — reviewed by nobody, and unpickable\n`
  + `afterwards, because a published tag must not be moved.\n`

/**
 * Phase B's consequence. Nothing sweeps these into anything — the tag names a
 * commit, not a working tree — which is precisely why they matter: they mean
 * the tree the releaser is reading is NOT the tree the tag publishes, and the
 * point of standing on the merged commit was that those two agree.
 */
export const NOT_THE_TREE_BEING_TAGGED =
  `The tag names the merged commit, so these changes will not be in it — which is\n`
  + `the problem: the tree you are looking at is not the tree the tag publishes,\n`
  + `and a published tag must not be moved once anyone has resolved it. Whatever\n`
  + `is in flight here belongs in its own PR, after the tag.\n`

/**
 * Why this working tree must not be released from, or `undefined` if it may.
 *
 * Only tracked modifications block — see the header for why untracked files do
 * not, and why `dist/` is deliberately NOT exempted even though the rebuild
 * step is about to write to it.
 *
 * `consequence` is the paragraph that says WHAT the modifications would do,
 * because the two phases have different answers and a guard that explains
 * itself with the wrong mechanism is a guard nobody trusts. Phase A's is
 * `git commit --all` sweeping them into the release commit; phase B's is that
 * the tree being read is not the tree the tag will name.
 */
export function cleanTreeObjection(porcelain: string, consequence: string = SWEPT_INTO_THE_COMMIT): string | undefined {
  const dirty = parseStatus(porcelain).filter((record) => !isUntracked(record))
  if (dirty.length === 0) return undefined
  return (
    `release: REFUSING to release from a dirty working tree.\n`
    + `\n`
    + `  ${dirty.length} tracked file(s) differ from HEAD:\n`
    + `\n`
    + dirty.map((record) => `    ${record.code} ${record.path}`).join("\n")
    + `\n`
    + `\n`
    + consequence
    + `\n`
    + `Commit them, or park them, and start again:\n`
    + `    git status\n`
    + `    git stash --include-untracked      # NOT in a shared worktree — see AGENTS.md\n`
  )
}

/** Untracked files are reported, not refused, so a missing file is noticed early. */
export function untrackedNote(porcelain: string): string | undefined {
  const untracked = parseStatus(porcelain).filter(isUntracked)
  if (untracked.length === 0) return undefined
  return (
    `release: ${untracked.length} untracked file(s) will NOT be part of this release:\n`
    + untracked.map((record) => `    ${record.path}`).join("\n")
  )
}

// --- the gates that must precede `bumpp` ---

/**
 * Run one `release-gates.ts` gate here, where a refusal is still free, and map
 * its report onto this script's exit codes: 0 ok · 1 refused · 2 could not run.
 *
 * `release-gates.ts` says a caller MUST treat 2 as non-blocking, because a gate
 * that fails closed on its own bugs takes the repo down with it. That argument
 * is about CI, where the cost of a false red is a wedged repository. Here the
 * trade is inverted and so is the answer: a refusal costs a re-run, a false PASS
 * costs a tag that must never be moved. So a gate that cannot run stops the
 * release — and it can only ever stop it BEFORE `bumpp`, which is the only
 * reason it is legitimate to fail closed at all.
 */
export function runGate(
  collect: () => GateReport,
  log: (line: string) => void,
  cannotRun: string,
): number {
  let report: GateReport
  try {
    report = collect()
  } catch (err) {
    log(`release: ${cannotRun} — ${err instanceof Error ? err.message : String(err)}`)
    return 2
  }
  log(renderFindings(report))
  if (gateExitCodeFor(report, "enforce") === 0) return 0
  log("\nrelease: REFUSING — nothing has been committed, tagged or pushed.")
  return 1
}

// --- the execute hook ---

/**
 * The command string handed to `bumpp -x`. Both paths are quoted because
 * `bumpp` tokenizes this with `args-tokenizer` before spawning, and a home
 * directory with a space in it would otherwise split into two argv entries.
 */
export function executeCommand(bun: string, script: string): string {
  return `"${bun}" "${script}" ${REBUILD_FLAG}`
}

/**
 * `bumpp`'s argv. `--all` is load-bearing twice over — see the header: it is
 * what makes the commit carry the index (and therefore the staged rebuild), and
 * it is what disables `bumpp`'s own clean-tree check, which is why this file
 * runs its own first.
 *
 * `--no-tag --no-push` IS WHAT MAKES THIS PHASE A. `bumpConfigDefaults` is
 * `{ commit: true, tag: true, push: true }`, so an unflagged `bumpp` tags the
 * branch commit and pushes it — and the tag is the half that cannot be undone,
 * because the squash merge rewrites that SHA and leaves the tag naming a commit
 * `main` never receives. `--no-push` goes with it rather than being left on: the
 * branch is pushed a step later WITH an upstream, and `bumpp`'s `gitPush` also
 * runs `git push --tags` whenever a tag exists, so the two flags belong
 * together. `commit` survives both — `normalizeOptions` builds it from
 * `raw.commit`, which still defaults to true — so the release commit is still
 * made, still with `--all`, still with the subject `releaseCommitSubject`
 * returns.
 *
 * `bumpp` moved out of `package.json`'s scripts and into this string, which is
 * why it is in knip's `ignoreDependencies`: knip reads binaries out of script
 * strings and cannot follow one into an array literal in TypeScript.
 */
export function bumppArgv(execute: string, extra: ReadonlyArray<string> = []): Array<string> {
  return ["x", "bumpp", "--all", "--no-tag", "--no-push", "--execute", execute, ...extra]
}

/**
 * `bumpp`'s confirmation prompt, answered when nobody can answer it.
 *
 * `bumpp` ends with an interactive `? Bump? › (Y/n)`. With no TTY it never
 * resolves, and the failure is not a hang — it is SILENT AND MISLEADING. On
 * v0.4.5 the prompt aborted, nothing was committed, the release branch was
 * pushed EMPTY, and the run died three steps later at `gh pr create`:
 *
 *     GraphQL: No commits between main and release/v0.4.5 (createPullRequest)
 *
 * which names neither `bumpp` nor a prompt. Recovering meant deleting the
 * branch on both sides and re-running with `--yes` — knowledge the caller had
 * no way to have.
 *
 * So the consent is supplied here rather than demanded from the caller. Only
 * when there is no TTY: an interactive release keeps the prompt, which is worth
 * having on the one command that rewrites `package.json`. An explicit `--yes`
 * or `-y` is left alone rather than duplicated.
 */
export function withNonInteractiveConsent(
  args: ReadonlyArray<string>,
  isInteractive: () => boolean,
): Array<string> {
  if (isInteractive()) return [...args]
  if (args.some((a) => a === "--yes" || a === "-y")) return [...args]
  return [...args, "--yes"]
}

// --- steps ---

/**
 * The environment inputs `prepack` would otherwise measure for itself,
 * overridable so the tests never depend on the Bun they happen to be running
 * under or on whether anything has been installed (`check:ops` runs off-pin and
 * with no `bun install`, routinely). Forwarded verbatim, and only when present:
 * `prepack` distinguishes "no `running` given, go measure" from "`running` is
 * `undefined`, i.e. not Bun at all" by key presence.
 */
export type PinOptions = Pick<PrepackOptions, "running" | "pinned" | "root" | "requirements">

function pinOptions(options: PinOptions): PinOptions {
  const pin: PinOptions = {}
  if ("running" in options) pin.running = options.running
  if (options.pinned !== undefined) pin.pinned = options.pinned
  if (options.root !== undefined) pin.root = options.root
  if (options.requirements !== undefined) pin.requirements = options.requirements
  return pin
}

export interface RebuildOptions extends PinOptions, ChangelogIo {
  git?: GitRunner
  run?: CommandRunner
  log?: (line: string) => void
  pathspecs?: ReadonlyArray<string>
  /** The rendered entry to insert. Handed over by `release()` via the env. */
  changelogBlock?: string
}

/**
 * Rebuild the committed artifacts against the version that is now on disk, write
 * the changelog entry, and stage both. Runs INSIDE `bumpp`, between the bump and
 * the commit — the only window where the new version is on disk and the commit
 * has not happened yet.
 *
 * `prepack()` is the rebuild rather than a local reimplementation: it is already
 * the argv-identical pair of builds (`build` + `build:lib`), it already refuses
 * off-pin before writing anything, and it already bundles with
 * `process.execPath`.
 *
 * The changelog is written LAST, after the builds have succeeded: a failed build
 * aborts `bumpp` before the commit, and the less of the tree that has been
 * touched by then the better. It is staged explicitly even though `--all` would
 * pick a tracked modification up anyway, so the hook is answerable for the whole
 * content of the release commit on its own terms.
 */
export function rebuildAndStage(options: RebuildOptions = {}): number {
  const log = options.log ?? ((line: string) => { console.error(line) })
  const git = options.git ?? realGit
  const pathspecs = options.pathspecs ?? stagePathspecs()

  const built = prepack({ ...pinOptions(options), run: options.run, log })
  if (built !== 0) return built

  const staged = git(stageArgv(pathspecs))
  if (staged.status !== 0) {
    log(`release: could not stage ${pathspecs.join(", ")} — ${staged.stderr.trim() || `git exited ${staged.status}`}`)
    return 2
  }
  log(`release: rebuilt and staged ${pathspecs.join(", ")}`)

  const block = options.changelogBlock
  if (block === undefined || block.trim() === "") return 0

  const objection = applyChangelog(block, options)
  if (objection !== undefined) {
    log(objection)
    return 2
  }
  const stagedNotes = git(["add", "--", CHANGELOG_FILE])
  if (stagedNotes.status !== 0) {
    log(`release: could not stage ${CHANGELOG_FILE} — ${stagedNotes.stderr.trim() || `git exited ${stagedNotes.status}`}`)
    return 2
  }
  log(`release: wrote and staged the ${CHANGELOG_FILE} entry`)
  return 0
}

// --- phase A: the branch and the PR ---

export interface PrepareOptions extends PinOptions, ChangelogIo {
  git?: GitRunner
  run?: CommandRunner
  gh?: GhRunner
  log?: (line: string) => void
  now?: () => Date
  /** The tag being cut — the milestone title, and the version `bumpp` bumps to. */
  tag?: string
  /** The interpreter the execute hook will bundle with. Never a PATH lookup. */
  bun?: string
  /** This file, as `bumpp` will have to spawn it. */
  script?: string
  /** Extra argv forwarded to `bumpp`. */
  bumppArgs?: ReadonlyArray<string>
  /**
   * Whether a human is there to answer `bumpp`'s confirmation prompt. Injectable
   * so the tests can drive both sides without owning a terminal.
   */
  isInteractive?: () => boolean
  /** Where the branch is pushed, and where gate 4 reads the existing tags. */
  remote?: string
  /** How the rendered block reaches the hook. Defaults to `process.env`. */
  handOverBlock?: (block: string | undefined) => void
}

/**
 * One `git` read whose output IS the answer, so a non-zero exit has to become a
 * message rather than an empty string. `trim: false` for a file's contents,
 * where trailing bytes are part of what was read.
 */
function gitLine(
  git: GitRunner,
  args: ReadonlyArray<string>,
  options: { trim?: boolean } = {},
): { value?: string; error?: string } {
  const res = git(args)
  if (res.status !== 0) {
    return {
      error: `git ${args.join(" ")} → exit ${res.status}: ${res.stderr.trim() || "(no stderr)"}`,
    }
  }
  return { value: options.trim === false ? res.stdout : res.stdout.trim() }
}

/**
 * PHASE A. Guard, assert, generate, bump — then branch, push, and open the PR.
 * The order is the point: everything that can refuse runs before anything is
 * written, and the first thing written is a local branch, which is the cheapest
 * thing in this file to throw away.
 *
 * The tree comes first because it is the failure nothing else in the repo
 * catches; then the pin, because the rebuild inside `bumpp` is what it guards;
 * then the two gates that read the world, cheapest first — gate 4 is two `git`
 * calls, gate 5 and the changelog are `gh` pipelines — and the changelog last of
 * all, because there is no point paying for it behind a refusal.
 *
 * THE BRANCH IS CREATED LAST OF THE PREPARATORY STEPS, immediately before
 * `bumpp`, so every refusal above it leaves the checkout on the branch it
 * started on. Below that line the failure modes are recoverable but not silent:
 * a failed `bumpp` leaves an empty release branch, a failed push leaves a
 * committed one, and a failed `gh pr create` leaves a pushed one. None of them
 * has cut a tag, which is the property that matters — see `tagRelease`.
 *
 * GATE 4 IS HERE EVEN THOUGH `tagRelease` RUNS IT AGAIN, because a tag collision
 * discovered now costs a re-run and one discovered after the PR has been
 * reviewed and merged costs a version. It is the same argument as the clean-tree
 * guard: refuse while refusing is free.
 *
 * GATE 5 IS HERE RATHER THAN LEFT TO `release:notes` because the changelog step
 * below is SKIPPED WHOLESALE — `gh` reads included — when `CHANGELOG.md` already
 * documents the version. An open PR in the milestone blocks a first attempt and
 * silently stops blocking the re-run, which is exactly when it matters. That
 * re-run is also the case that needs the release PR to be EXEMPT from gate 5:
 * by then this phase's own pull request is open in the milestone being cut. See
 * `releaseCommitSubject`.
 */
export function prepare(options: PrepareOptions = {}): number {
  const log = options.log ?? ((line: string) => { console.error(line) })
  const git = options.git ?? realGit
  const gh = options.gh ?? realGh
  const run = options.run ?? realRunner
  const bun = options.bun ?? process.execPath
  const script = options.script ?? import.meta.path
  const remote = options.remote ?? DEFAULT_REMOTE
  const tag = options.tag

  if (tag === undefined || !TAG_RE.test(tag)) {
    log(usage(tag))
    return 1
  }

  const status = git(["status", "--porcelain"])
  if (status.status !== 0) {
    log(`release: could not read the working tree — ${status.stderr.trim() || `git exited ${status.status}`}`)
    return 2
  }
  const objection = cleanTreeObjection(status.stdout)
  if (objection !== undefined) {
    log(objection)
    return 1
  }
  const note = untrackedNote(status.stdout)
  if (note !== undefined) log(note)

  const pinned = prepack({ ...pinOptions(options), checkOnly: true, run, log })
  if (pinned !== 0) return pinned

  const ordered = runGate(
    () => collectTagOrderGate(tag, { git, remote }),
    log,
    "could not read the tags this release must be ahead of",
  )
  if (ordered !== 0) return ordered

  const open = runGate(
    () => collectOpenPrGate(tag, { gh }),
    log,
    "could not read the open pull requests",
  )
  if (open !== 0) return open

  const plan = planChangelog({ tag, gh, read: options.read, now: options.now })
  if (plan.objection !== undefined) {
    log(plan.objection)
    return 1
  }
  if (plan.note !== undefined) log(plan.note)

  // --- everything below this line writes ---

  const branch = releaseBranch(tag)
  const switched = git(["switch", "-c", branch])
  if (switched.status !== 0) {
    log(branchObjection(branch, switched.stderr))
    return 1
  }
  log(`release: on ${branch}`)

  const handOver = options.handOverBlock ?? ((block: string | undefined) => {
    if (block === undefined) delete process.env[CHANGELOG_ENV]
    else process.env[CHANGELOG_ENV] = block
  })

  handOver(plan.block)
  const bumppArgs = withNonInteractiveConsent(
    ["--release", stripV(tag), ...options.bumppArgs ?? []],
    options.isInteractive ?? (() => process.stdin.isTTY === true),
  )
  const bumped = run(bun, bumppArgv(executeCommand(bun, script), bumppArgs))
  handOver(undefined)
  if (bumped.status !== 0) {
    log(`release: bumpp exited ${bumped.status}${bumped.output ? ` — ${bumped.output.trim()}` : ""}`)
    return 2
  }

  const pushed = git(["push", "--set-upstream", remote, branch])
  if (pushed.status !== 0) {
    log(`release: could not push ${branch} to ${remote} — ${pushed.stderr.trim() || `git exited ${pushed.status}`}`)
    return 2
  }

  // No milestone. A release commit belongs to none by convention (see
  // `RELEASE_COMMIT_RE`), and assigning one would put this PR into the notes of
  // the very release it is cutting the moment anyone re-read the milestone.
  const created = gh([
    "pr", "create",
    "--head", branch,
    "--title", releaseCommitSubject(tag),
    "--body", releasePrBody(tag),
  ])
  if (created.status !== 0) {
    log(
      `release: ${branch} is pushed, but \`gh pr create\` exited ${created.status} — ${created.stderr.trim() || "(no stderr)"}\n`
      + `\n`
      + `Nothing is tagged. Open the PR by hand with the SAME title, which is what\n`
      + `exempts it from gate 5, then continue with \`bun run release:tag ${tag}\`:\n`
      + `    gh pr create --head ${branch} --title ${JSON.stringify(releaseCommitSubject(tag))} --body …\n`,
    )
    return 2
  }

  log(
    `release: ${branch} is pushed and the PR is open.\n`
    + `${created.stdout.trim()}\n`
    + `\n`
    + `NO TAG HAS BEEN CUT. Once the PR is merged:\n`
    + `    bun run release:tag ${tag}\n`,
  )
  return 0
}

/** Why phase A must not start on this branch name. */
export function branchObjection(branch: string, stderr: string): string {
  return (
    `release: REFUSING — could not start \`${branch}\`.\n`
    + `\n`
    + `  ${stderr.trim() || "(git said nothing)"}\n`
    + `\n`
    + `Most likely it already exists, from an attempt that got further than this one.\n`
    + `Nothing has been written. Check what is on it before deleting it — a branch\n`
    + `carrying a finished release commit only needs pushing and a PR:\n`
    + `    git log --oneline ${DEFAULT_BASE}..${branch}\n`
  )
}

// --- phase B: the tag ---

/** `version` out of a `package.json`, or undefined if there is not one to read. */
export function manifestVersion(source: string): string | undefined {
  try {
    const parsed = JSON.parse(source) as { version?: unknown }
    return typeof parsed.version === "string" ? parsed.version : undefined
  } catch {
    return undefined
  }
}

/**
 * Why the merged manifest is not the one this tag may be cut against.
 *
 * This is gate 3 asked at the only moment it can be answered for certain: the
 * tag is about to be created on THIS tree, so comparing the tag against THIS
 * tree's `package.json` is the whole of the assertion. `release:check version`
 * and `release-tag-check.yml` ask the same question earlier and later
 * respectively; this is the one that can still prevent.
 */
export function mergedManifestObjection(
  tag: string,
  source: string,
  where: string,
): string | undefined {
  const version = manifestVersion(source)
  if (version === undefined) {
    return (
      `release: REFUSING — could not read a version out of ${where}'s package.json.\n`
      + `\n`
      + `The tag is cut against that tree, so a manifest that cannot be parsed is a\n`
      + `tag that cannot be justified.\n`
    )
  }
  if (version.trim() === stripV(tag)) return undefined
  return (
    `release: REFUSING — ${where} reads version \`${version}\`, not \`${stripV(tag)}\`.\n`
    + `\n`
    + `The release PR for \`${tag}\` has not merged, or it merged something else. A tag\n`
    + `whose commit disagrees with it has already shipped here once —\n`
    + `\`git show v0.1.1:package.json\` reads \`0.1.0\` — and a published tag must never\n`
    + `be moved, so this is refused rather than reported afterwards.\n`
    + `\n`
    + `    bun run release:prepare ${tag}     # if the PR was never opened\n`
    + `    gh pr list --head release/${tag}   # if it is open and unmerged\n`
  )
}

/**
 * GitHub's squash-merge subject suffix, anchored to the END of the line only.
 * `feat: x (#1) and more` is not a suffix and is not stripped.
 */
export const SQUASH_PR_SUFFIX = /\s+\(#\d+\)$/u

/**
 * Why the merged head is not the release commit, and therefore must not be
 * tagged. `mergedManifestObjection` above asks what the tip's
 * `package.json` says; it cannot ask whether the tip IS the release. An ordinary
 * PR does not bump the version, so anything merged between the release PR
 * landing and this command running leaves the manifest reading X.Y.Z while the
 * tag quietly captures commits no CHANGELOG entry describes. Several agents open
 * PRs here in parallel, so that window is not theoretical — v0.4.4 came close.
 *
 * THE SUBJECT IS THE IDENTITY, and comparing the tip's TREE or its touched paths
 * would be worse, not stronger. There is nothing to compare a tree against:
 * phase B builds nothing by design (see `tagRelease`), so an expected tree could
 * only come from rebuilding on the pinned Bun, which is the whole of phase A. A
 * path set is worse still — `dist/lib`'s chunk names are content hashes, and the
 * changelog step is skipped wholesale when the entry is already there, so the
 * release commit's own path set legitimately varies. Meanwhile a subject is not
 * a unique identifier ON ITS OWN, but it is not being asked to be one: the tip
 * must ALSO carry a manifest reading exactly X.Y.Z, and the only commit that
 * does both is the one `bumpp` made. This is also the identity the rest of the
 * repo already runs on — squash-merge turns the PR title into the subject,
 * `release-gates.ts` exempts the release PR by matching it, and the tag
 * annotation is it — so nothing new has to be believed for this to hold.
 *
 * AND THAT SAME SQUASH APPENDS ` (#N)`. GitHub's squash merge uses the PR title
 * as the subject and adds the PR number to it, so the commit this is looking at
 * is `chore: release v0.4.4 (#84)` and never the bare
 * `releaseCommitSubject(tag)`. Comparing the two verbatim refuses EVERY genuine
 * release — which is what this function did when it was first written, because
 * its rehearsal drove a fake `git` whose subjects had no suffix. `main`'s own
 * history is the counter-example: `dc725c9 chore: release v0.4.4 (#84)`. So the
 * suffix is stripped before the comparison, and only the suffix — an ordinary
 * PR that merged on top carries its own title underneath one, and still
 * refuses.
 */
export function notTheReleaseCommitObjection(
  tag: string,
  subject: string,
  merged: string,
  remote: string,
  base: string,
): string | undefined {
  const expected = releaseCommitSubject(tag)
  if (subject.trim().replace(SQUASH_PR_SUFFIX, "") === expected) return undefined
  return (
    `release: REFUSING — ${remote}/${base} is at \`${merged.slice(0, 12)}\`, whose subject is\n`
    + `\n`
    + `    ${subject.trim() || "(no subject)"}\n`
    + `\n`
    + `  and not \`${expected}\`.\n`
    + `\n`
    + `Something merged on top of the release PR. The check above cannot see it —\n`
    + `an ordinary PR does not touch the version, so package.json still reads\n`
    + `${stripV(tag)} — and tagging here would publish commits the ${CHANGELOG_FILE} entry for\n`
    + `\`${tag}\` does not describe.\n`
    + `\n`
    + `Find the release commit and tag THAT: it is on \`${base}\`, and its tree is exactly\n`
    + `what the changelog says \`${tag}\` is. Whatever landed after it ships in the next\n`
    + `release:\n`
    + `    git log --oneline ${remote}/${base}\n`
    + `    git tag -a ${tag} -m ${JSON.stringify(expected)} <that sha> && git push ${remote} ${tag}\n`
  )
}

/**
 * Why this checkout is not standing where the tag has to be cut.
 *
 * Phase B could tag a SHA it never checked out, and refusing instead is
 * deliberate: the tree the releaser is looking at is then the tree the tag names,
 * so `git show`, a local test run and the tag cannot disagree. It also makes the
 * clean-tree check below mean something — on a detached SHA it would be checking
 * a tree nobody is about to tag.
 */
export function notOnMergedHeadObjection(
  head: string,
  merged: string,
  remote: string,
  base: string,
): string | undefined {
  if (head === merged) return undefined
  return (
    `release: REFUSING — this checkout is at \`${head.slice(0, 12)}\`, but ${remote}/${base} is at\n`
    + `\`${merged.slice(0, 12)}\`.\n`
    + `\n`
    + `The tag has to name the commit the squash merge actually produced, and it is\n`
    + `cut on the tree you are looking at so the two cannot disagree:\n`
    + `    git switch ${base} && git merge --ff-only ${remote}/${base}\n`
  )
}

export interface TagOptions {
  git?: GitRunner
  log?: (line: string) => void
  /** The tag being cut. Must already be the merged manifest's version. */
  tag?: string
  /** Where the merged commit is fetched from, and where the tag is pushed. */
  remote?: string
  /** The branch the release PR merged into. */
  base?: string
}

/**
 * PHASE B. Fetch, assert, gate, tag, push — the four lines a squash merge makes
 * necessary.
 *
 * WHY THIS IS NOT PART OF PHASE A. A squash merge creates a NEW commit with a
 * new SHA. A tag created in phase A would point at the branch commit, which
 * `main` never receives, so the tag would name content nobody can reach from the
 * default branch and `bindings:check` on `main` would be describing a different
 * tree from the one the tag publishes. There is no ordering inside one process
 * that fixes that; the merge has to have happened first.
 *
 * WHAT IT ASSERTS, AND WHY EACH ONE. The fetch is the only write it makes, and
 * it writes nothing this repo tracks. Then: the merged manifest must read
 * exactly this version (gate 3, asked against the tree being tagged); that
 * merged head must be the release commit and not something that landed on top
 * of it (`notTheReleaseCommitObjection`, which is the only assertion here that
 * can see a merge inside the review window); the checkout must BE that commit
 * with a clean tree, so the tree the releaser is looking at is the tree the tag
 * names; and gate 4 runs last, because after the PR has sat open for review,
 * another agent's tag is likelier than it was in phase A — this is now the last
 * line before the tag exists.
 *
 * `git push origin vX.Y.Z` is unrestricted: both of this repo's rulesets are
 * `target: branch` and there is no tag ruleset, so the bypass that used to carry
 * the release commit was never needed for the tag. That push is what fires
 * `release-tag-check.yml` and `publish-package.yml`.
 */
export function tagRelease(options: TagOptions = {}): number {
  const log = options.log ?? ((line: string) => { console.error(line) })
  const git = options.git ?? realGit
  const remote = options.remote ?? DEFAULT_REMOTE
  const base = options.base ?? DEFAULT_BASE
  const tag = options.tag

  if (tag === undefined || !TAG_RE.test(tag)) {
    log(usage(tag))
    return 1
  }

  const fetched = git(["fetch", remote, base])
  if (fetched.status !== 0) {
    log(`release: could not fetch ${remote}/${base} — ${fetched.stderr.trim() || `git exited ${fetched.status}`}`)
    return 2
  }

  // FETCH_HEAD rather than `refs/remotes/${remote}/${base}`: it is what the
  // fetch above just wrote, whatever refspec this clone happens to be
  // configured with, so the SHA compared below cannot be a stale tracking ref.
  const merged = gitLine(git, ["rev-parse", "FETCH_HEAD"])
  if (merged.error !== undefined) {
    log(`release: ${merged.error}`)
    return 2
  }
  const head = gitLine(git, ["rev-parse", "HEAD"])
  if (head.error !== undefined) {
    log(`release: ${head.error}`)
    return 2
  }

  const manifest = gitLine(git, ["show", `${merged.value}:package.json`], { trim: false })
  if (manifest.error !== undefined) {
    log(`release: ${manifest.error}`)
    return 2
  }
  const mismatch = mergedManifestObjection(tag, manifest.value ?? "", `${remote}/${base}`)
  if (mismatch !== undefined) {
    log(mismatch)
    return 1
  }

  // Beside the manifest read, because it is the same question about the same
  // object: that read says what the tip CONTAINS, this one says what it IS. It
  // is ahead of `notOnMergedHeadObjection` on purpose — that objection's remedy
  // is `git merge --ff-only`, and sending a releaser to fast-forward onto a tip
  // that is then refused anyway makes the real diagnosis the second thing they
  // see. `log -1`, not `show -s`, so it cannot be confused with the read above.
  const subject = gitLine(git, ["log", "-1", "--format=%s", merged.value ?? ""])
  if (subject.error !== undefined) {
    log(`release: ${subject.error}`)
    return 2
  }
  const overtaken = notTheReleaseCommitObjection(tag, subject.value ?? "", merged.value ?? "", remote, base)
  if (overtaken !== undefined) {
    log(overtaken)
    return 1
  }

  const misplaced = notOnMergedHeadObjection(head.value ?? "", merged.value ?? "", remote, base)
  if (misplaced !== undefined) {
    log(misplaced)
    return 1
  }

  const status = git(["status", "--porcelain"])
  if (status.status !== 0) {
    log(`release: could not read the working tree — ${status.stderr.trim() || `git exited ${status.status}`}`)
    return 2
  }
  const dirty = cleanTreeObjection(status.stdout, NOT_THE_TREE_BEING_TAGGED)
  if (dirty !== undefined) {
    log(dirty)
    return 1
  }

  const ordered = runGate(
    () => collectTagOrderGate(tag, { git, remote }),
    log,
    "could not read the tags this release must be ahead of",
  )
  if (ordered !== 0) return ordered

  // `-a`, never a lightweight tag: the runbook has always required an annotated
  // one and nothing else in the repo checks it. The message is the release
  // commit's subject, which is what every tag from v0.4.1 onwards carries.
  const tagged = git(["tag", "-a", tag, "-m", releaseCommitSubject(tag), merged.value ?? ""])
  if (tagged.status !== 0) {
    log(`release: could not create ${tag} — ${tagged.stderr.trim() || `git exited ${tagged.status}`}`)
    return 2
  }

  const pushed = git(["push", remote, tag])
  if (pushed.status !== 0) {
    log(
      `release: ${tag} exists LOCALLY but could not be pushed to ${remote} — ${pushed.stderr.trim() || `git exited ${pushed.status}`}\n`
      + `\n`
      + `Nothing downstream has fired. Either push it, or delete it and start again:\n`
      + `    git push ${remote} ${tag}\n`
      + `    git tag -d ${tag}\n`,
    )
    return 2
  }

  log(
    `release: ${tag} is cut on ${merged.value?.slice(0, 12)} and pushed to ${remote}.\n`
    + `release-tag-check.yml and publish-package.yml fire on it.`,
  )
  return 0
}

// --- entry point ---

/**
 * Refusal text for a missing or malformed tag, or a missing phase. Never a guess
 * at what was meant — and never a default phase either: doing the wrong one of
 * these silently is the whole hazard the split introduced.
 */
export function usage(given?: string): string {
  return (
    `release: REFUSING — ${given === undefined ? "no release tag was given." : `\`${given}\` is not a release tag.`}\n`
    + `\n`
    + `  usage: bun run release:prepare vX.Y.Z [bumpp flags]   # branch, commit, PR\n`
    + `         bun run release:tag vX.Y.Z                     # once that PR merges\n`
    + `\n`
    + `Nothing pushes to \`${DEFAULT_BASE}\` outside a pull request, so the release lands in two\n`
    + `phases. \`prepare\` bumps and commits on \`release/vX.Y.Z\` and opens the PR, and\n`
    + `cuts NO tag; \`tag\` cuts the annotated tag on the MERGED head, which is the only\n`
    + `commit that exists — a squash merge rewrites the branch's SHA.\n`
    + `\n`
    + `The tag names the GitHub milestone the CHANGELOG entry is generated from, and\n`
    + `it is what \`bumpp\` bumps package.json to, so the tag and the manifest cannot\n`
    + `disagree. Prereleases are not modelled by any of this tooling.\n`
  )
}

/** Refusal text for an argv that names no phase. */
export function subcommandObjection(given?: string): string {
  return (
    `release: REFUSING — ${given === undefined ? "no phase was named." : `\`${given}\` is not a phase.`}\n`
    + `\n`
    + `  expected \`${SUBCOMMANDS.join("` or `")}\` as the first argument.\n`
    + `\n`
    + `${usage(undefined).split("\n").slice(2).join("\n")}`
  )
}

export interface ParsedArgv {
  /** Which phase, when the argv names one. */
  subcommand?: Subcommand
  tag?: string
  rebuild: boolean
  /** Everything left over, forwarded verbatim to `bumpp`. */
  bumppArgs: Array<string>
  /** Set when the argv itself is the problem. */
  objection?: string
}

/**
 * Split this script's own argv from `bumpp`'s.
 *
 * THE PHASE IS THE FIRST ARGUMENT and is only ever read from position 0, so
 * `bumpp`'s `-t <template>` cannot be mistaken for the `tag` phase. There is no
 * default: the two phases do very different things, and inferring one from an
 * argv that named neither is how somebody ends up opening a second release PR
 * when they meant to tag the first.
 *
 * The tag is then claimed positionally, but only from an item that LOOKS like a
 * tag and does not sit where a forwarded flag's value would — `-t v9.9.9` names
 * `bumpp`'s tag template, not this release. `--release` is refused outright
 * rather than forwarded: the version comes from the tag, and two sources for it
 * is exactly how `v0.1.1` was tagged off a `0.1.0` manifest.
 *
 * `--no-publish` is recognised here and produces nothing — see
 * `NO_PUBLISH_FLAG`. Being in `OWN_FLAGS` is the whole of its handling: it is
 * consumed rather than forwarded, and no longer selects between two behaviours
 * because there is only one.
 */
export function parseArgv(argv: ReadonlyArray<string>): ParsedArgv {
  const parsed: ParsedArgv = {
    rebuild: argv.includes(REBUILD_FLAG),
    bumppArgs: [],
  }
  const first = argv[0]
  const named = first !== undefined && (SUBCOMMANDS as ReadonlyArray<string>).includes(first)
  if (named) parsed.subcommand = first as Subcommand
  const rest = named ? argv.slice(1) : argv
  for (const [index, arg] of rest.entries()) {
    if (OWN_FLAGS.includes(arg)) continue
    if (arg === "--release") {
      parsed.objection =
        `release: REFUSING — \`--release\` is not forwarded.\n`
        + `\n`
        + `  The version comes from the tag: \`bun run release:prepare vX.Y.Z\` bumps\n`
        + `  package.json to X.Y.Z, so the tag and the manifest cannot disagree.\n`
      return parsed
    }
    const previous = rest[index - 1]
    const couldBeAValue = previous !== undefined && previous.startsWith("-") && !OWN_FLAGS.includes(previous)
    if (parsed.tag === undefined && !couldBeAValue && TAG_RE.test(arg)) {
      parsed.tag = arg
      continue
    }
    parsed.bumppArgs.push(arg)
  }
  return parsed
}

export function main(
  argv: ReadonlyArray<string> = process.argv.slice(2),
  options: PrepareOptions & TagOptions & RebuildOptions = {},
): number {
  const log = options.log ?? ((line: string) => { console.error(line) })
  const parsed = parseArgv(argv)
  if (parsed.rebuild) {
    return rebuildAndStage({
      ...options,
      changelogBlock: options.changelogBlock ?? process.env[CHANGELOG_ENV],
    })
  }
  if (parsed.objection !== undefined) {
    log(parsed.objection)
    return 1
  }
  if (parsed.subcommand === undefined) {
    log(subcommandObjection(argv[0]))
    return 1
  }
  const tag = options.tag ?? parsed.tag
  if (parsed.subcommand === "tag") return tagRelease({ ...options, tag })
  return prepare({
    ...options,
    tag,
    bumppArgs: options.bumppArgs ?? parsed.bumppArgs,
  })
}

if (import.meta.main) {
  process.exit(main())
}
