export const BRIDGE_CHANNELS = {
  lifecycleCurrent: 'maximal:lifecycle/current',
  proxyUrl: 'maximal:connection/proxy-url',
  openExternal: 'maximal:native/open-external',
  authStatus: 'maximal:control/auth-status',
  authStart: 'maximal:control/auth-start',
  authCancel: 'maximal:control/auth-cancel',
  authSignOut: 'maximal:control/auth-sign-out',
  accountsList: 'maximal:control/accounts-list',
  accountsSwitch: 'maximal:control/accounts-switch',
  observabilityOverview: 'maximal:control/observability-overview',
  observabilityRequests: 'maximal:control/observability-requests',
  observabilityRequest: 'maximal:control/observability-request',
  connectionsList: 'maximal:control/connections-list',
  connectionsAct: 'maximal:control/connections-act',
  connectionsRevealCredential: 'maximal:control/connections-reveal-credential',
  appsList: 'maximal:control/apps-list',
  appsSetEnabled: 'maximal:control/apps-set-enabled',
  apiKeysList: 'maximal:control/api-keys-list',
  apiKeysCreate: 'maximal:control/api-keys-create',
  apiKeysUpdate: 'maximal:control/api-keys-update',
  apiKeysRemove: 'maximal:control/api-keys-remove',
  apiKeysSetEnforcement: 'maximal:control/api-keys-set-enforcement',
  modelsList: 'maximal:control/models-list',
  modelsRefresh: 'maximal:control/models-refresh',
  localModelsList: 'maximal:control/local-models-list',
  localModelsEnsure: 'maximal:control/local-models-ensure',
  localModelsCancel: 'maximal:control/local-models-cancel',
  usageGet: 'maximal:control/usage-get',
  diagnosticsGet: 'maximal:control/diagnostics-get',
  logsLocation: 'maximal:native/logs-location',
  logsReveal: 'maximal:native/logs-reveal',
  localModelsOpenFolder: 'maximal:native/local-models-open-folder',
  pendingSettingsRequest: 'maximal:menu/pending-settings-request',
  menuBarModeGet: 'maximal:native/menu-bar-mode-get',
  menuBarModeBeginEnable: 'maximal:native/menu-bar-mode-begin-enable',
  menuBarModeConfirmEnable: 'maximal:native/menu-bar-mode-confirm-enable',
  menuBarModeCancelEnable: 'maximal:native/menu-bar-mode-cancel-enable',
  menuBarModeDisable: 'maximal:native/menu-bar-mode-disable',
  terminalSpawn: 'maximal:terminal/spawn',
  terminalWrite: 'maximal:terminal/write',
  terminalResize: 'maximal:terminal/resize',
  terminalAck: 'maximal:terminal/ack',
  terminalTerminate: 'maximal:terminal/terminate',
  terminalList: 'maximal:terminal/list',
  terminalProfiles: 'maximal:terminal/profiles',
  terminalDiscover: 'maximal:terminal/discover',
  terminalLaunch: 'maximal:terminal/launch',
  lifecycleChanged: 'maximal:lifecycle/changed',
  controlChanged: 'maximal:control/changed',
  localModelsChanged: 'maximal:control/local-models-changed',
  menuOpenSettings: 'maximal:menu/open-settings',
  trafficInvalidated: 'maximal:control/traffic-invalidated',
  terminalData: 'maximal:terminal/data',
  terminalExit: 'maximal:terminal/exit',
  harnessHide: 'maximal:harness/hide',
  harnessProvider: 'maximal:harness/provider',
  harnessAsk: 'maximal:harness/ask',
  harnessAbort: 'maximal:harness/abort',
  harnessApprove: 'maximal:harness/approve',
  harnessEnsureModel: 'maximal:harness/ensure-model',
  harnessDelta: 'maximal:harness/delta',
  harnessTool: 'maximal:harness/tool',
  harnessApproval: 'maximal:harness/approval',
  harnessEnd: 'maximal:harness/end',
  harnessModelProgress: 'maximal:harness/model-progress',
} as const

export const INVOKE_CHANNELS = [
  BRIDGE_CHANNELS.lifecycleCurrent,
  BRIDGE_CHANNELS.proxyUrl,
  BRIDGE_CHANNELS.openExternal,
  BRIDGE_CHANNELS.authStatus,
  BRIDGE_CHANNELS.authStart,
  BRIDGE_CHANNELS.authCancel,
  BRIDGE_CHANNELS.authSignOut,
  BRIDGE_CHANNELS.accountsList,
  BRIDGE_CHANNELS.accountsSwitch,
  BRIDGE_CHANNELS.observabilityOverview,
  BRIDGE_CHANNELS.observabilityRequests,
  BRIDGE_CHANNELS.observabilityRequest,
  BRIDGE_CHANNELS.connectionsList,
  BRIDGE_CHANNELS.connectionsAct,
  BRIDGE_CHANNELS.connectionsRevealCredential,
  BRIDGE_CHANNELS.appsList,
  BRIDGE_CHANNELS.appsSetEnabled,
  BRIDGE_CHANNELS.apiKeysList,
  BRIDGE_CHANNELS.apiKeysCreate,
  BRIDGE_CHANNELS.apiKeysUpdate,
  BRIDGE_CHANNELS.apiKeysRemove,
  BRIDGE_CHANNELS.apiKeysSetEnforcement,
  BRIDGE_CHANNELS.modelsList,
  BRIDGE_CHANNELS.modelsRefresh,
  BRIDGE_CHANNELS.localModelsList,
  BRIDGE_CHANNELS.localModelsEnsure,
  BRIDGE_CHANNELS.localModelsCancel,
  BRIDGE_CHANNELS.usageGet,
  BRIDGE_CHANNELS.diagnosticsGet,
  BRIDGE_CHANNELS.logsLocation,
  BRIDGE_CHANNELS.logsReveal,
  BRIDGE_CHANNELS.localModelsOpenFolder,
  BRIDGE_CHANNELS.pendingSettingsRequest,
  BRIDGE_CHANNELS.menuBarModeGet,
  BRIDGE_CHANNELS.menuBarModeBeginEnable,
  BRIDGE_CHANNELS.menuBarModeConfirmEnable,
  BRIDGE_CHANNELS.menuBarModeCancelEnable,
  BRIDGE_CHANNELS.menuBarModeDisable,
  BRIDGE_CHANNELS.terminalProfiles,
  BRIDGE_CHANNELS.terminalDiscover,
  BRIDGE_CHANNELS.terminalLaunch,
  BRIDGE_CHANNELS.terminalSpawn,
  BRIDGE_CHANNELS.terminalWrite,
  BRIDGE_CHANNELS.terminalResize,
  BRIDGE_CHANNELS.terminalTerminate,
  BRIDGE_CHANNELS.terminalList,
  BRIDGE_CHANNELS.terminalAck,
  BRIDGE_CHANNELS.harnessHide,
  BRIDGE_CHANNELS.harnessProvider,
  BRIDGE_CHANNELS.harnessAsk,
  BRIDGE_CHANNELS.harnessAbort,
  BRIDGE_CHANNELS.harnessApprove,
  BRIDGE_CHANNELS.harnessEnsureModel,
] as const

export const EVENT_CHANNELS = [
  BRIDGE_CHANNELS.lifecycleChanged,
  BRIDGE_CHANNELS.controlChanged,
  BRIDGE_CHANNELS.localModelsChanged,
  BRIDGE_CHANNELS.menuOpenSettings,
  BRIDGE_CHANNELS.trafficInvalidated,
  BRIDGE_CHANNELS.terminalData,
  BRIDGE_CHANNELS.terminalExit,
  BRIDGE_CHANNELS.harnessDelta,
  BRIDGE_CHANNELS.harnessTool,
  BRIDGE_CHANNELS.harnessApproval,
  BRIDGE_CHANNELS.harnessEnd,
  BRIDGE_CHANNELS.harnessModelProgress,
] as const
