export const BRIDGE_CHANNELS = {
  lifecycleCurrent: 'maximal:lifecycle/current',
  proxyUrl: 'maximal:connection/proxy-url',
  openExternal: 'maximal:native/open-external',
  authStatus: 'maximal:control/auth-status',
  authStart: 'maximal:control/auth-start',
  authCancel: 'maximal:control/auth-cancel',
  authSignOut: 'maximal:control/auth-sign-out',
  accountsList: 'maximal:control/accounts-list',
  accountsSwitch: 'maximal:control/accounts-switch',
  observabilityOverview: 'maximal:control/observability-overview',
  observabilityRequests: 'maximal:control/observability-requests',
  observabilityRequest: 'maximal:control/observability-request',
  connectionsList: 'maximal:control/connections-list',
  connectionsAct: 'maximal:control/connections-act',
  connectionsRevealCredential: 'maximal:control/connections-reveal-credential',
  appsList: 'maximal:control/apps-list',
  appsSetEnabled: 'maximal:control/apps-set-enabled',
  apiKeysList: 'maximal:control/api-keys-list',
  apiKeysCreate: 'maximal:control/api-keys-create',
  apiKeysUpdate: 'maximal:control/api-keys-update',
  apiKeysRemove: 'maximal:control/api-keys-remove',
  apiKeysSetEnforcement: 'maximal:control/api-keys-set-enforcement',
  modelsList: 'maximal:control/models-list',
  modelsRefresh: 'maximal:control/models-refresh',
  usageGet: 'maximal:control/usage-get',
  diagnosticsGet: 'maximal:control/diagnostics-get',
  logsLocation: 'maximal:native/logs-location',
  logsReveal: 'maximal:native/logs-reveal',
  pendingSettingsRequest: 'maximal:menu/pending-settings-request',
  menuBarModeGet: 'maximal:native/menu-bar-mode-get',
  menuBarModeBeginEnable: 'maximal:native/menu-bar-mode-begin-enable',
  menuBarModeConfirmEnable: 'maximal:native/menu-bar-mode-confirm-enable',
  menuBarModeCancelEnable: 'maximal:native/menu-bar-mode-cancel-enable',
  menuBarModeDisable: 'maximal:native/menu-bar-mode-disable',
  lifecycleChanged: 'maximal:lifecycle/changed',
  controlChanged: 'maximal:control/changed',
  menuOpenSettings: 'maximal:menu/open-settings',
  trafficInvalidated: 'maximal:control/traffic-invalidated',
} as const

export const INVOKE_CHANNELS = [
  BRIDGE_CHANNELS.lifecycleCurrent,
  BRIDGE_CHANNELS.proxyUrl,
  BRIDGE_CHANNELS.openExternal,
  BRIDGE_CHANNELS.authStatus,
  BRIDGE_CHANNELS.authStart,
  BRIDGE_CHANNELS.authCancel,
  BRIDGE_CHANNELS.authSignOut,
  BRIDGE_CHANNELS.accountsList,
  BRIDGE_CHANNELS.accountsSwitch,
  BRIDGE_CHANNELS.observabilityOverview,
  BRIDGE_CHANNELS.observabilityRequests,
  BRIDGE_CHANNELS.observabilityRequest,
  BRIDGE_CHANNELS.connectionsList,
  BRIDGE_CHANNELS.connectionsAct,
  BRIDGE_CHANNELS.connectionsRevealCredential,
  BRIDGE_CHANNELS.appsList,
  BRIDGE_CHANNELS.appsSetEnabled,
  BRIDGE_CHANNELS.apiKeysList,
  BRIDGE_CHANNELS.apiKeysCreate,
  BRIDGE_CHANNELS.apiKeysUpdate,
  BRIDGE_CHANNELS.apiKeysRemove,
  BRIDGE_CHANNELS.apiKeysSetEnforcement,
  BRIDGE_CHANNELS.modelsList,
  BRIDGE_CHANNELS.modelsRefresh,
  BRIDGE_CHANNELS.usageGet,
  BRIDGE_CHANNELS.diagnosticsGet,
  BRIDGE_CHANNELS.logsLocation,
  BRIDGE_CHANNELS.logsReveal,
  BRIDGE_CHANNELS.pendingSettingsRequest,
  BRIDGE_CHANNELS.menuBarModeGet,
  BRIDGE_CHANNELS.menuBarModeBeginEnable,
  BRIDGE_CHANNELS.menuBarModeConfirmEnable,
  BRIDGE_CHANNELS.menuBarModeCancelEnable,
  BRIDGE_CHANNELS.menuBarModeDisable,
] as const

export const EVENT_CHANNELS = [
  BRIDGE_CHANNELS.lifecycleChanged,
  BRIDGE_CHANNELS.controlChanged,
  BRIDGE_CHANNELS.menuOpenSettings,
  BRIDGE_CHANNELS.trafficInvalidated,
] as const
