export {
  acknowledgePty,
  copyPty,
  copyPtyOwnership,
  configurePty,
  defaultShell,
  discoverTerminalTargets,
  grantPtyProjection,
  killAllPtys,
  killPty,
  launchTerminal,
  listTerminalProfiles,
  listPtys,
  resizePty,
  spawnPty,
  syncPtyPane,
  transferPty,
  transferPtyOwnership,
  transferPtyProjection,
  writePty,
} from '../main/native/pty.js';