export {
  acknowledgePty,
  configurePty,
  defaultShell,
  discoverTerminalTargets,
  grantPtyProjection,
  killAllPtys,
  killPty,
  launchTerminal,
  listTerminalProfiles,
  listPtys,
  resizePty,
  spawnPty,
  writePty,
} from '../main/native/pty.js';