#!/usr/bin/env bun
/**
 * Generate `src/generated/ui-embed.ts` from the built UI in
 * `shell/dist/ui/`, so the proxy's single-file `bun build --compile`
 * binary carries the settings + dashboard assets inside it — the same
 * `import … with { type: "file" }` embedding the dashboard always used,
 * just generated to cover hashed filenames.
 *
 * Run AFTER scripts/build-ui.ts and BEFORE `bun build --compile`
 * (build-sidecar.ts wires this). In dev/tests the committed stub (empty
 * UI_FILES) is used instead, and the proxy serves from `shell/dist` on
 * disk — see src/routes/ui/route.ts.
 */
import { readdirSync, statSync } from "node:fs"
import { join, relative, resolve } from "node:path"

import { contentTypeForPath } from "../src/lib/platform/web-content-types"

const REPO = resolve(import.meta.dir, "..")
const DIST = join(REPO, "shell/dist/ui")
const OUT = join(REPO, "src/generated/ui-embed.ts")

function walk(dir: string): Array<string> {
  const out: Array<string> = []
  for (const name of readdirSync(dir)) {
    const full = join(dir, name)
    if (statSync(full).isDirectory()) out.push(...walk(full))
    else out.push(full)
  }
  return out
}

const files = walk(DIST).sort()
const imports: Array<string> = []
const entries: Array<string> = []

files.forEach((file, i) => {
  // URL path the proxy serves this asset at: /ui/<dist-relative-path>.
  const urlPath = "/ui/" + relative(DIST, file).split(/[\\/]/).join("/")
  // Import specifier relative to src/generated/ui-embed.ts.
  const spec = relative(join(REPO, "src/generated"), file).split(/[\\/]/).join("/")
  imports.push(`import _${i} from "${spec}" with { type: "file" }`)
  entries.push(`  ${JSON.stringify(urlPath)}: { path: _${i} as unknown as string, type: ${JSON.stringify(contentTypeForPath(file))} },`)
})

const banner = `// GENERATED by scripts/gen-ui-embed.ts — do not edit.
// Lists the built UI assets embedded into the compiled proxy binary.
// In dev/tests this file is the empty stub and the proxy serves from
// shell/dist on disk instead (see src/routes/ui/route.ts).
`

const body = `${banner}${imports.join("\n")}

export interface UiEmbedEntry {
  /** Embedded file path (a \\$bunfs path inside the compiled binary). */
  path: string
  /** Content-Type to serve the asset with. */
  type: string
}

export const UI_FILES: Record<string, UiEmbedEntry | undefined> = {
${entries.join("\n")}
}
`

await Bun.write(OUT, body)
console.error(`[gen-ui-embed] wrote ${files.length} entries → ${relative(REPO, OUT)}`)
